name: Eusebius Stinkmorchel
favicon: null
layout_spectrum: 0.562615254893899
typography_spectrum: 0.7828230869490653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6569820619188249
  lightness: 0.9792472985573113
  saturation: 0.7039112304337323
  rhythmicContrast: 0.6961812316440046
purpose: []
